name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm i
      - run: npm run fmt:check
      - run: npm run test
      - run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}
          files: ./coverage/lcov.info
